### ISSUE TITLE
Cám ơn SSI đã cung cấp API client tuy nhiên documentation cần cụ thể và cập nhật thường xuyên hơn

### ISSUE THREAD

**Issue by thinh-vu** [SSI-Securities-Corporation/python-fctrading#1]
Cám ơn team SSI đã cung cấp API client để hỗ trợ các nhà đầu tư tiếp cận và phát triển giao dịch thuật toán. Mình tìm hiểu về API được cung cấp nhưng cũng gặp nhiều khó khăn do document hiện tại đọc tương đối khó hiểu, chưa kể có những chi tiết thừa và gây rối. Bản thân mình trải nghiệm thì thấy rằng những hướng dẫn để sử dụng client ở mức cơ bản, với fc_data mình còn dùng được nhưng fc_trading thì chưa biết nó hoạt động ra sao vì khi chạy file example với terminal xong thấy đứng yên mặc dù print access_token ra màn hình. Mình cũng phản ánh với bạn quản lý tài khoản trong tuần trước về link gắn kèm trên website SSI iBoard không thể download được client vì lỗi 410. Ý kiến cá nhân mình là nếu các bạn bỏ công xây dựng phần mềm tốt thì tuyệt hơn nữa nếu có thể đầu tư thêm chút công sức để cập nhật tài liệu hướng dẫn, cung cấp các ví dụ trực quan và có ích để người dùng có thể dễ tiếp cận và sử dụng tốt những gì các bạn đã thiết kế. 
Một số ví dụ về tài liệu hướng dẫn:
1. Không phải ai cũng cần cài đặt client qua proxy, nếu các bạn hướng dẫn cho người dùng nội bộ có thể ghi rõ thành mục riêng. Khi mình là người mới và đọc tài liệu tưởng đâu phải chạy luôn lệnh cài đặt proxy hay từ file tarball nhưng lòng vòng 1 hồi hóa ra có thể cài đặt trực tiếp từ pypi. Tại sao không đưa lựa chọn này đầu tiên? Người dùng chỉ cần pip install ... đã xong rồi, ai gặp lỗi hãy đi tiếp.
2. Link truy cập docs Swaggers không hoạt động http://127.0.0.1:8000/docs. Nếu tài liệu không xem được, video hướng dẫn không có, mình nghĩ sẽ rất khó để khách hàng có thể sử dụng sản phẩm của bạn dù sản phẩm tốt thế nào.
Đây là 2 ví dụ nhỏ mình gặp phải và nhận thấy các bạn có thể cập nhật những thứ bé tí ti này để nâng cao trải nghiệm người dùng.
Anw, Cám ơn team và chúc các bạn xây dựng các sản phẩm hỗ trợ nhà đầu tư tốt hơn nữa.

**Comment by ssidevelopment** [comment]
Cảm ơn phản hồi của bạn. Chúng tôi đã có hướng dẫn sử dụng online, mời bạn tham khảo tại 
[https://guide.ssi.com.vn/ssi-products/fastconnect-trading/huong-dan-ket-noi](url)

**Comment by thinh-vu** [comment]
Cám ơn @ssidevelopment đã phản hồi. Cám ơn team đã lắng nghe ý kiến góp ý và phát hành hướng dẫn sử dụng online kịp thời. Chúc các bạn phát triển sản phẩm API thành công hơn nữa.
